version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: henrys_postgres
    environment:
      POSTGRES_DB: henrys_smartstock
      POSTGRES_USER: henrys_user
      POSTGRES_PASSWORD: henrys_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U henrys_user -d henrys_smartstock"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: henrys_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: henrys_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://henrys_user:henrys_password@postgres:5432/henrys_smartstock
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data: